### ISSUE TITLE
BUG: Module is always set to use 2014-10-10 as the APIversion.

### ISSUE THREAD

**Issue by PeterSelchDahl** [tiander/OMSsearchAPI#1]
Hi Tiander,
Richard Rundle found the reason why I couldn't use the OMS Search Powershell Module for Europe West. The module is hardcoded to use 2014-10-10 as the API version.

Using this workaround solved my issue:

As a workaround you can try adding the following two lines to the runbook:
$APIVersion = $OMSConnection.APIVersion # add this at line 18

$Results = Search-OMSWorkspace -Token $Token -Subscription $SubID -Workspace $Workspace -Region $Region -APIVersion "2015-03-20" -Query $Query

Comment out the existing $Results line (line 24).

**Comment by tiander** [comment]
Hi Peter,
Thanks for reporting. I'm adding Richard's workaround to my blogpost.

Tiander.
